### ISSUE TITLE
openai::completions::CompletionBuilder::presence_penalty requests i8 but docs request a float between -2.0 and 2.0

### ISSUE THREAD

**Issue by deavid** [rellfy/openai#1]
### Bug Description

https://docs.rs/openai/1.0.0-alpha.9/openai/completions/struct.CompletionBuilder.html#method.presence_penalty

presence penalty and frequency penalty are i8 but the API requests a float between -2.0 and 2.0. 

I have a slight suspicion that it might be applying some scaling (i.e. dividing by 10.0 before sending) but I can't find any proof on the code of this.

Anyway, whatever it is, it needs to be either corrected or clarified. If it's really sending an integer, the problem is that the only options here are -2,-1,0,1,2; if it's actually sending a fractional number, the documentation doesn't explain.

There might be other methods affected by this issue in this repo. I'd recommend checking if it applies. For example frequency_penalty in this struct seems to have the same problem. It's possible this also is on other APIs too.

### Reproduction Steps

https://docs.rs/openai/1.0.0-alpha.9/openai/completions/struct.CompletionBuilder.html#method.presence_penalty

Try to send an API request with presence penalty of 0.32. Won't compile..

### Expected Behavior

https://docs.rs/openai/1.0.0-alpha.9/openai/completions/struct.CompletionBuilder.html#method.presence_penalty

API accepting a float, fixed number or docs updated to explain how decimal numbers can be sent to the API.

### Library Version

1.0.0-alpha.9

### rustc Version

rustc 1.68.2 (9eb3afe9e 2023-03-27)

### cargo Version

cargo 1.68.2 (6feb7c9cf 2023-03-26)

### Platform

Linux

**Comment by rellfy** [comment]
Hi there, thanks for reporting the problem. This should have been resolved by #7 and is included in the latest release. Please let us know if that's not the case.
