### ISSUE TITLE
Make BASE_URL customizable

### ISSUE THREAD

**Issue by Guyutongxue** [rellfy/openai#16]
### Problem

I prefer not using OpenAI's official API endpoint `https://api.openai.com/v1/`, but some mirror site like [chatanywhere/GPT_API_free](https://github.com/chatanywhere/GPT_API_free).

### Solution

Seems that this feature is easy to implement, just make `BASE_URL` in `lib.rs` customizable -- export a function like `set_key`; for example `set_base_url`.

**Comment by AlbertMarashi** [comment]
Would you like to have a go at implementing this?

**Comment by rellfy** [comment]
FYI I'll have some time to work on this (and any other open issues) only in a month or so.
If anyone can get to it before that, great :)

**Comment by Guyutongxue** [comment]
lol I've already made a fork to add this feature ([Guyutongxue/openai-rs](https://github.com/Guyutongxue/openai-rs)) but, well, with using of `once_cell::Lazy`. Not a good practice for a Rust project...

**Comment by rellfy** [comment]
> lol I've already made a fork to add this feature ([Guyutongxue/openai-rs](https://github.com/Guyutongxue/openai-rs/tree/custom-url)) but, well, with using of `once_cell::Lazy`. Not a good practice for a Rust project...

I agree, but it's still better than nothing. We should also eventually refactor out the global API key. Although I think it's unlikely a project would hit 2 different APIs, but still we shouldn't assume.
